# Site settings
author: Trey Jennings
title: Why Software Engineering
header-img: img/home-bg.png
email: tjennings343@gmail.com
copyright_name: Trey Jennings
description: > # this means to ignore newlines until "baseurl:"
  Why I'm here
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tjennings343

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
